require("miklakapi.core.diagnostics")
require("miklakapi.core.options")
require("miklakapi.core.keymaps")
require("miklakapi.core.autocmds")
require("miklakapi.core.commands")
require("miklakapi.lazy")
